data:
  batch_size: 4
  num_workers: 8
  train_ann: multimodal-data/USDATASET/train_annotation.CSV
  train_dir: multimodal-data/USDATASET/images/train
  val_ann: multimodal-data/USDATASET/test_annotation.CSV
  val_dir: multimodal-data/USDATASET/images/test
model:
  config_path: groundingdino/config/GroundingDINO_SwinT_OGC.py
  # lora_weights: weights/ObjectName/freez_1/best_model.pth
  lora_weights: weights/20250530_2033/best_model.pth
  # lora_weights: weights/ObjectName/freez_7/best_model.pth
  # lora_weights: weights/ObjectName/freez_7/checkpoint_epoch_15.pth
  # lora_weights: weights/groundingdino_swint_ogc.pth
  weights_path: weights/groundingdino_swint_ogc.pth
  # weights_path: weights/20250530_1648/best_model.pth
  
training:
  learning_rate: 0.01
  num_epochs: 200
  save_dir: weights
  save_frequency: 5
  use_lora: true
  visualization_frequency: 5
  warmup_epochs: 5
