data:
  train_dir: multimodal-data/train
  train_ann: multimodal-data/train.CSV
  val_dir: multimodal-data/val
  val_ann: multimodal-data/val.CSV
  batch_size: 4
  num_workers: 8

model:
  config_path: groundingdino/config/GroundingDINO_SwinT_OGC.py
  weights_path: weights/groundingdino_swint_ogc.pth

training:
  num_epochs: 500
  learning_rate: 5e-4
  save_dir: weights
  save_frequency: 5
  warmup_epochs: 5
  use_lora: true
  visualization_frequency: 5
  patient: 15
