data:
  train_dir: multimodal-data/Breast/images/train
  train_ann: multimodal-data/Breast/train_annotation.CSV
  val_dir: multimodal-data/Breast/images/val
  val_ann: multimodal-data/Breast/val_annotation.CSV
  batch_size: 4
  num_workers: 8

model:
  config_path: groundingdino/config/GroundingDINO_SwinT_OGC.py
  weights_path: weights/groundingdino_swint_ogc.pth

training:
  num_epochs: 500
  learning_rate: 1e-3
  save_dir: weights
  save_frequency: 15
  warmup_epochs: 5
  use_lora: true
  visualization_frequency: 15
  patient: 100
